### ISSUE TITLE
[Предложение] По умолчанию искать версию x64 и только потом x86

### ISSUE THREAD

**Issue by ovcharenko-di** [oscript-library/v8find#11]
На данный момент в библиотеке установлен приоритет поиска x86 -> x64.

Моя проблема в том, что я выполняю `runner session kill` на сервере, где установлены обе версии платформы. Версия x86 установлена только для целей работы со Снегопатом, без дополнительных компонентов типа rac/ras. vanessa-runner не передает требуемую разрядность в библиотеку v8find, поэтому v8find успешно находит каталог x86 платформы, но вот файла rac там ожидаемо нет.

Я бы хотел изменить приоритет поиска хотя бы потому, что сейчас практически везде устанавливается именно x64.
Если будет реализована #10, тогда и эта проблема тоже должна уйти, но приоритет поиска я бы все равно изменил.

Строка с разрядностью, о которой идет речь:
https://github.com/khorevaa/v8find/blob/a4a79590b3ffaafbbed72219b1ffd3b577329657/src/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%9F%D0%BB%D0%B0%D1%82%D1%84%D0%BE%D1%80%D0%BC%D0%B01%D0%A1.os#L191

**Comment by nixel2007** [comment]
В деплойке висит пулл-реквест с параметром для разрядности платформы. Кажется, его стоит довести до ума и просто портировать в vanessa-runner :)

**Comment by ovcharenko-di** [comment]
> В деплойке висит пулл-реквест с параметром для разрядности платформы. Кажется, его стоит довести до ума и просто портировать в vanessa-runner :)

Уже merged! Но спасибо за инфомацию, учту
https://github.com/oscript-library/deployka/pull/47

**Comment by khorevaa** [comment]
Приоритет х86 оставлен для совместимости работы v8runner. 
Поэтому предлагаю ничего не менять.
